hokey:
  pokey:
    lyrics: >
      You put your {bodyPart} in.
      You put your {bodyPart} out.
      You put your {bodyPart} in, and you shake it all about.
      You do the hokey-pokey and turn yourself around.
      That's what it's all about.
